/*
    Generated by Atomist on 06 07 2016 
*/
package com.jackietreehornpublishing;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Russrest1Application {

    public static void main(String[] args) {
        SpringApplication.run(Russrest1Application.class, args);
    }
}
